apiVersion: apps/v1
kind: Deployment
metadata:
  name: ieat-frontend
  labels:
    app: ieat-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ieat-frontend
  template:
    metadata:
      labels:
        app: ieat-frontend
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        fsGroup: 1001
      containers:
        - name: ieat-frontend
          image: bigbigna1/ieat-frontend:latest
          ports:
            - containerPort: 3000
              name: http
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: ieat-frontend-svc
spec:
  selector:
    app: ieat-frontend
  ports:
    - protocol: TCP
      port: 3008
      targetPort: 3000
  type: ClusterIP
