apiVersion: apps/v1
kind: Deployment
metadata:
  name: target-app
  labels:
    app: target-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: target-app
  template:
    metadata:
      labels:
        app: target-app
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 101 # nginx user in nginxinc/nginx-unprivileged
        fsGroup: 101
      containers:
        - name: nginx
          image: nginxinc/nginx-unprivileged:alpine
          ports:
            - containerPort: 8080
              name: http
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 3
            periodSeconds: 3
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: target-app-svc
spec:
  selector:
    app: target-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
